Repository Hold-Krykke/Security_and_FullstackJavascript_Exam, pull requests merged in 2020-06, with the labels that each got.

#52 Fixed JWT check at startup
  Backend/src/resolverMap.ts
  Backend/src/schema/schema.graphql
  FindYourFriends/constants/settings.js
  FindYourFriends/facade.js
  FindYourFriends/screens/LoginScreen.js
  FindYourFriends/screens/UserScreen.jsx
Labels: BUG, READY FOR MERGE, React Native Application, Security

#56 Added updateLocation mutation to the facade (frontend)
  FindYourFriends/constants/settings.js
  FindYourFriends/facade.js
  FindYourFriends/screens/MapScreen.js
Labels: React Native Application

#59 Added proper error handling in Create User Screen
  FindYourFriends/screens/CreateUserScreen.jsx
Labels: React Native Application

#58 Fixing keyboard covers input
  FindYourFriends/components/Card.js
  FindYourFriends/components/Header.js
  FindYourFriends/screens/CreateUserScreen.jsx
  FindYourFriends/screens/LoginScreen.js
  FindYourFriends/screens/UserScreen.jsx
Labels: BUG, READY FOR MERGE, React Native Application

#46 Refreshtoken
  Backend/package.json
  Backend/src/resolverMap.ts
  Backend/src/routes/refreshToken.ts
  Backend/src/server.ts
  Backend/test/userFacadeTest.ts
  FindYourFriends/App.js
  FindYourFriends/constants/settings.js
  FindYourFriends/screens/LoginScreen.js
  FindYourFriends/screens/MapScreen.js
  FindYourFriends/screens/UserScreen.jsx
  FindYourFriends/utils/ApolloClientProvider.js
  FindYourFriends/utils/ErrorHandler.js
Labels: Security

#19 MapView in-progress
  FindYourFriends/App.js
  FindYourFriends/components/MapScreenSettings.js
  FindYourFriends/package-lock.json
  FindYourFriends/package.json
  FindYourFriends/screens/LoginScreen.js
  FindYourFriends/screens/MapScreen.js
Labels: READY FOR MERGE, React Native Application
